supsign/iofvolunteers

_ide_helper.php
_ide_helper_models.php
app/Http/Controllers/VolunteerController.php
app/Http/Requests/GuestRegister.php
app/View/Components/Person/CountriesForm.php
composer.json
composer.lock
database/migrations/2021_05_18_084730_create_skills_table.php
database/migrations/2021_05_18_090854_create_duties_table.php
resources/views/layouts/app.blade.php
routes/web.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-15 by the Git Integration for Jira app.

IOF-15: Merge IOF-15-Submenu-Volunteer to master

---

resources/css/style.css
resources/views/guest/register.blade.php
resources/views/host/register.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-19 by the Git Integration for Jira app.

IOF-19: Merge IOF-19-Disclaimer to master

---

resources/css/style.css
resources/views/components/person/genders-form.blade.php
resources/views/guest/register.blade.php
resources/views/host/register.blade.php
resources/views/project/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-17 by the Git Integration for Jira app.

IOF-17: Merge IOF-17-Darstellung-Volunteer to master

---

resources/views/layouts/app.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-18 by the Git Integration for Jira app.

IOF-18: Merge IOF-18-register-button to master

---

app/Http/Requests/VolunteerRegister.php
app/View/Components/Person/GendersForm.php
resources/css/style.css
resources/views/components/language/experience-form.blade.php
resources/views/components/orienteering/competitor-experience-dropdown.blade.php
resources/views/components/orienteering/competitor-experience-form.blade.php
resources/views/components/orienteering/disciplines-form.blade.php
resources/views/components/orienteering/skills-form.blade.php
resources/views/components/person/continents-form.blade.php
resources/views/components/person/countries-form.blade.php
resources/views/components/person/genders-form.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-14 by the Git Integration for Jira app.

IOF-14: Merge IOF-14-register-as-volunteer-validation to master

---

app/Http/Controllers/VolunteerController.php
app/Http/Requests/VolunteerEdit.php
app/Http/Requests/VolunteerRegister.php
app/View/Components/Language/ExperienceForm.php
app/View/Components/Orienteering/CompetitorExperienceForm.php
app/View/Components/Orienteering/DisciplinesForm.php
app/View/Components/Orienteering/SkillsForm.php
app/View/Components/Person/ContinentsForm.php
app/View/Components/Person/CountriesForm.php
app/View/Components/Person/GendersForm.php
package-lock.json
resources/views/components/language/experience-form.blade.php
resources/views/components/orienteering/competitor-experience-form.blade.php
resources/views/components/orienteering/disciplines-form.blade.php
resources/views/components/orienteering/skills-form.blade.php
resources/views/components/person/continents-form.blade.php
resources/views/components/person/countries-form.blade.php
resources/views/components/person/genders-form.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php
routes/web.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-21 by the Git Integration for Jira app.

IOF-21: Merge IOF-21-volunteer-edit to master

---

app/Console/Kernel.php
resources/css/media.css
resources/css/style.css

Pull request created in: https://supsign.atlassian.net/browse/IOF-23 by the Git Integration for Jira app.

IOF-23: Merge IOF-23-minor-code-issues to master

---

app/Http/Controllers/VolunteerController.php
resources/views/components/orienteering/skills-form.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-22 by the Git Integration for Jira app.

IOF-22: Merge IOF-22-continentCheckboxAny to master

---

resources/css/style.css
resources/views/components/orienteering/competitor-experience-form.blade.php
resources/views/components/orienteering/skills-form.blade.php
resources/views/components/person/continents-form.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-27 by the Git Integration for Jira app.

IOF-27: Merge IOF-27-css-forms to master

---

app/Http/Controllers/VolunteerController.php
resources/css/style.css
resources/views/volunteer/search.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-35 by the Git Integration for Jira app.

IOF-35: Merge IOF-35-volunteer-search to master

---

resources/views/components/base/textarea.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-55 by the Git Integration for Jira app.

IOF-55: Merge IOF-55-amposant-darstellung-bug to master

---

app/Http/Controllers/VolunteerController.php
app/Models/VolunteerCollection.php
resources/views/volunteer/search.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-13 by the Git Integration for Jira app.

Merge IOF-13-backend-volunteer-search to master

---

database/migrations/2021_08_30_072515_change_timestamp_on_table_volunteers.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-75 by the Git Integration for Jira app.

Merge IOF-75-change-timestamp-to-datetime-for-birthdate to master

---

resources/views/mails/volunteer/contact.blade.php
resources/views/volunteer/register.blade.php
resources/views/volunteer/search.blade.php
resources/views/volunteer/searchList.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-79 by the Git Integration for Jira app.

IOF-79: Merge IOF-79-textkorrekturen to master

---

app/Http/Requests/Volunteer/Register.php
app/Http/Requests/Volunteer/Update.php
database/migrations/2021_09_01_074306_other_lang_volunteer.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/preview.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-81 by the Git Integration for Jira app.

Merge IOF-81-erweitertung-sprache to master

---

package-lock.json
resources/js/main.js
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-80 by the Git Integration for Jira app.

IOF-80: Merge IOF-80-required-anpassen to master

---

app/Http/Controllers/ProjectController.php
app/Http/Requests/Project/Update.php
package-lock.json
resources/js/main.js
resources/views/project/edit.blade.php
resources/views/project/preview.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-87 by the Git Integration for Jira app.

IOF-87: Merge IOF-87-project-edit to master

---

resources/views/volunteer/search.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-95 by the Git Integration for Jira app.

IOF-95: Merge IOF-95-volunteer-search-anpassen to master

---

resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-94 by the Git Integration for Jira app.

IOF-94: Merge IOF-94-titel-ändern-register-edit to master

---

app/Http/Requests/Project/Register.php
resources/views/project/preview.blade.php
resources/views/volunteer/preview.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-98 by the Git Integration for Jira app.

IOF-98: Merge IOF-98-fehler-abfangen-preview-both to master

---

app/Http/Requests/Guest/Register.php
app/Http/Requests/Guest/Update.php
app/Http/Requests/Host/Register.php
app/Http/Requests/Host/Update.php
app/Http/Requests/Project/Register.php
app/Http/Requests/Project/Update.php
resources/css/style.css
resources/views/guest/edit.blade.php
resources/views/guest/register.blade.php
resources/views/home.blade.php
resources/views/host/edit.blade.php
resources/views/host/register.blade.php
resources/views/project/edit.blade.php
resources/views/project/preview.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php
resources/views/volunteer/search.blade.php
resources/views/volunteer/searchList.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-120 by the Git Integration for Jira app.

IOF-120: Merge IOF-120-color-coding to master

---

app/Http/Requests/Guest/Register.php
app/Http/Requests/Guest/Update.php
app/Http/Requests/Host/Register.php
app/Http/Requests/Host/Update.php
app/Http/Requests/Project/Register.php
app/Http/Requests/Project/Update.php
app/Models/Guest.php
resources/js/main.js
resources/views/components/base/input.blade.php
resources/views/components/base/radio.blade.php
resources/views/guest/edit.blade.php
resources/views/guest/register.blade.php
resources/views/guest/search.blade.php
resources/views/guest/searchList.blade.php
resources/views/home.blade.php
resources/views/host/edit.blade.php
resources/views/host/register.blade.php
resources/views/project/preview.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/preview.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-119 by the Git Integration for Jira app.

IOF-119: Merge IOF-119-kundenfeedback-anpassungen to master

---

app/Models/Guest.php
resources/js/main.js
resources/views/guest/search.blade.php
resources/views/guest/searchList.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/preview.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-121 by the Git Integration for Jira app.

IOF-121: Merge IOF-121-korrekturen-teil-2 to master

---

package-lock.json
resources/views/project/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-118 by the Git Integration for Jira app.

IOF-118: Merge IOF-118-hinweise-webseite-eintragen-http to master

---

app/Mail/ContactHostMail.php
app/Mail/ContactVolunteerMail.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-125 by the Git Integration for Jira app.

IOF-125: Merge IOF-125-mail-anpassungen to master

---

resources/views/layouts/app.blade.php
resources/views/project/list.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-130 by the Git Integration for Jira app.
┆Issue is synchronized with this [Jira Task](https://supsign.atlassian.net/browse/IOF-134) by [Unito](https://www.unito.io)

IOF-130: Merge IOF-130-rename-list-projects to master

---

resources/views/guest/edit.blade.php
resources/views/guest/register.blade.php
resources/views/host/edit.blade.php
resources/views/host/register.blade.php
resources/views/project/edit.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/register.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-129 by the Git Integration for Jira app.
┆Issue is synchronized with this [Jira Task](https://supsign.atlassian.net/browse/IOF-135) by [Unito](https://www.unito.io)

IOF-129: Merge IOF-129-improve-text-in-forms to master

---

resources/views/volunteer/searchList.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-136 by the Git Integration for Jira app.

IOF-136: Merge IOF-136-umbau-beschriftung-von-erfahrung to master

---

app/Http/Controllers/VolunteerController.php
resources/css/style.css
resources/views/guest/edit.blade.php
resources/views/guest/preview.blade.php
resources/views/guest/register.blade.php
resources/views/guest/search.blade.php
resources/views/project/edit.blade.php
resources/views/project/register.blade.php
resources/views/volunteer/edit.blade.php
resources/views/volunteer/preview.blade.php
resources/views/volunteer/register.blade.php
resources/views/volunteer/search.blade.php
resources/views/volunteer/searchList.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-139 by the Git Integration for Jira app.

IOF-139: Merge IOF-139-experiences to master

---

resources/css/style.css
resources/views/auth/login.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-141 by the Git Integration for Jira app.

IOF-141: Merge IOF-141-register-note-auf-login-form to master

---

routes/web.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-144 by the Git Integration for Jira app.

IOF-144: Merge IOF-144-routes-migration-zu-laravel-9 to master

---

resources/views/layouts/app.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-145 by the Git Integration for Jira app.

IOF-145: Merge IOF-145-kontaktadresse to master

---

resources/views/layouts/app.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-148 by the Git Integration for Jira app.

IOF-148: Merge IOF-148-supsign-schriftzug-auf-iof-webseite to master

---

.idea/blade.xml
.idea/git_toolbox_prj.xml
.idea/php.xml
app/Http/Controllers/ContactController.php
app/Http/Controllers/ContinentController.php
app/Http/Controllers/Controller.php
app/Http/Controllers/CountryController.php
app/Http/Controllers/GuestController.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/HostController.php
app/Http/Controllers/MediaDownloadController.php
app/Http/Controllers/ProjectController.php
app/Http/Controllers/VolunteerController.php
database/migrations/2022_04_12_080330_add_active_status.php
resources/css/style.css
resources/views/components/base/toggleActive.blade.php
resources/views/guest/edit.blade.php
resources/views/host/edit.blade.php
resources/views/project/edit.blade.php
resources/views/volunteer/edit.blade.php
routes/web.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-147 by the Git Integration for Jira app.

Merge IOF-147-soft-delete-ergaenzen to master

---

resources/views/host/preview.blade.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-149 by the Git Integration for Jira app.

IOF-149: Merge IOF-149-host-gast to master

---

app/Mail/ContactProjectMail.php
app/Providers/AppServiceProvider.php

Pull request created in: https://supsign.atlassian.net/browse/IOF-151 by the Git Integration for Jira app.

Merge IOF-151-mail-project-volunteer-reply-to-addresse-checken to master
